version: "latest"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace

#  mysql:
#    image: mysql:8.3.0
#    ports:
#      - 3306:3306
#    expose:
#      - '3306'
#    environment:
#      MYSQL_DATABASE: 'db'
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: 'password'
#      MYSQL_ROOT_PASSWORD: 'password'