version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10s; poetry run; python src/main.py;"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"

