version: "latest"
services:

  aula7:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 'python3 aula7/main.py'
    ports:
      - "8001:8001"
    volumes:
      - .:/workspace
    networks:
      - app_network

  ollama:
    image: ollama/ollama:0.1.30
    ports:
      - 11434:11434
    expose:
      - '11434'
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge